[package]
name = "image_processor"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.99"
craby = "0.1.0-rc"
cxx = { version = "1.0.187", features = ["c++20"] }
image = "0.25.9"
base64 = "0.22"

[build-dependencies]
craby_build = { version = "0.1.0-rc", features = ["cxx"] }

[lib]
name = "imageprocessor"
crate-type = ["staticlib"]
