// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "cxx.h"
#include "ffi.rs.h"
#include <react/bridging/Bridging.h>
#include <variant>
#include <iterator>
#include <algorithm>

using namespace facebook;

namespace imageprocessor {

class RustVecBuffer : public jsi::MutableBuffer {
public:
  explicit RustVecBuffer(rust::Vec<uint8_t> vec)
    : vec_(std::move(vec)) {}

  ~RustVecBuffer() override = default;

  size_t size() const override {
    return vec_.size();
  }

  uint8_t* data() override {
    return const_cast<uint8_t*>(vec_.data());
  }

private:
  rust::Vec<uint8_t> vec_;
};

} // namespace imageprocessor

namespace facebook {
namespace react {

template <>
struct Bridging<std::monostate> {
  static std::monostate fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    return std::monostate{};
  }

  static jsi::Value toJs(jsi::Runtime& rt, const std::monostate& value) {
    return jsi::Value::undefined();
  }
};

template <>
struct Bridging<rust::Str> {
  static rust::Str fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::Str(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Str& value) {
    return react::bridging::toJs(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::String> {
  static rust::String fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto str = value.asString(rt).utf8(rt);
    return rust::String(str.data(), str.size());
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::String& value) {
    return react::bridging::toJs(rt, std::string(value.data(), value.size()));
  }
};

template <>
struct Bridging<rust::Vec<uint8_t>> {
  static rust::Vec<uint8_t> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arrayBuffer = value.asObject(rt).getArrayBuffer(rt);
    uint8_t* data = arrayBuffer.data(rt);
    size_t size = arrayBuffer.size(rt);
    rust::Vec<uint8_t> vec;
    vec.reserve(size);

    std::copy(data, data + size, std::back_inserter(vec));

    return vec;
  }

  static jsi::Value toJs(jsi::Runtime& rt, const rust::Vec<uint8_t>& vec) {
    auto buffer = std::make_shared<imageprocessor::RustVecBuffer>(std::move(vec));
    return jsi::ArrayBuffer(rt, buffer);
  }
};

template <typename T>
struct Bridging<rust::Vec<T>> {
  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> vec;
    vec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto element = arr.getValueAtIndex(rt, i);
      vec.push_back(react::bridging::fromJs<T>(rt, element, callInvoker));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto jsElement = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, jsElement);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::imageprocessor::bridging::ImageResult> {
  static craby::imageprocessor::bridging::ImageResult fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$base64 = obj.getProperty(rt, "base64");
    auto obj$width = obj.getProperty(rt, "width");
    auto obj$height = obj.getProperty(rt, "height");
    auto obj$format = obj.getProperty(rt, "format");

    auto _obj$base64 = react::bridging::fromJs<rust::String>(rt, obj$base64, callInvoker);
    auto _obj$width = react::bridging::fromJs<double>(rt, obj$width, callInvoker);
    auto _obj$height = react::bridging::fromJs<double>(rt, obj$height, callInvoker);
    auto _obj$format = react::bridging::fromJs<rust::String>(rt, obj$format, callInvoker);

    craby::imageprocessor::bridging::ImageResult ret = {
      _obj$base64,
      _obj$width,
      _obj$height,
      _obj$format
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::imageprocessor::bridging::ImageResult value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$base64 = react::bridging::toJs(rt, value.base_64);
    auto _obj$width = react::bridging::toJs(rt, value.width);
    auto _obj$height = react::bridging::toJs(rt, value.height);
    auto _obj$format = react::bridging::toJs(rt, value.format);

    obj.setProperty(rt, "base64", _obj$base64);
    obj.setProperty(rt, "width", _obj$width);
    obj.setProperty(rt, "height", _obj$height);
    obj.setProperty(rt, "format", _obj$format);

    return jsi::Value(rt, obj);
  }
};

} // namespace react
} // namespace facebook
