// Auto generated by Craby. DO NOT EDIT.
#include "CxxImageProcessorModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace imageprocessor {
namespace modules {

std::string CxxImageProcessorModule::dataPath = std::string();

CxxImageProcessorModule::CxxImageProcessorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxImageProcessorModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::imageprocessor::bridging::ImageProcessor>(
    craby::imageprocessor::bridging::createImageProcessor(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::imageprocessor::bridging::ImageProcessor *ptr) { rust::Box<craby::imageprocessor::bridging::ImageProcessor>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::imageprocessor::utils::ThreadPool>(10);
  methodMap_["loadImage"] = MethodMetadata{1, &CxxImageProcessorModule::loadImage};
}

CxxImageProcessorModule::~CxxImageProcessorModule() {
  invalidate();
}

void CxxImageProcessorModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxImageProcessorModule::loadImage(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxImageProcessorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    react::AsyncPromise<craby::imageprocessor::bridging::ImageResult> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0]() mutable {
      try {
        auto ret = craby::imageprocessor::bridging::loadImage(*it_, arg0);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::imageprocessor::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::imageprocessor::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace imageprocessor
} // namespace craby
