// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::image_processor_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::imageprocessor::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct ImageResult {
        uri: String,
        width: f64,
        height: f64,
        format: String,
        size: f64,
        compression_ratio: f64,
    }

    extern "Rust" {
        type ImageProcessor;

        #[cxx_name = "createImageProcessor"]
        fn create_image_processor(id: usize, data_path: &str) -> Box<ImageProcessor>;

        #[cxx_name = "compress"]
        fn image_processor_compress(it_: &mut ImageProcessor, quality: f64, format: &str) -> Result<()>;

        #[cxx_name = "crop"]
        fn image_processor_crop(it_: &mut ImageProcessor, x: f64, y: f64, width: f64, height: f64) -> Result<()>;

        #[cxx_name = "flip"]
        fn image_processor_flip(it_: &mut ImageProcessor, horizontal: bool) -> Result<()>;

        #[cxx_name = "resize"]
        fn image_processor_resize(it_: &mut ImageProcessor, width: f64, height: f64, fit: &str) -> Result<()>;

        #[cxx_name = "rotate"]
        fn image_processor_rotate(it_: &mut ImageProcessor, degrees: f64) -> Result<()>;

        #[cxx_name = "save"]
        fn image_processor_save(it_: &mut ImageProcessor) -> Result<ImageResult>;

        #[cxx_name = "setFilePath"]
        fn image_processor_set_file_path(it_: &mut ImageProcessor, path: &str) -> Result<()>;
    }
}

fn create_image_processor(id: usize, data_path: &str) -> Box<ImageProcessor> {
    let ctx = Context::new(id, data_path);
    Box::new(ImageProcessor::new(ctx))
}

fn image_processor_compress(it_: &mut ImageProcessor, quality: f64, format: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.compress(quality, format);
        ret
    })
}

fn image_processor_crop(it_: &mut ImageProcessor, x: f64, y: f64, width: f64, height: f64) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.crop(x, y, width, height);
        ret
    })
}

fn image_processor_flip(it_: &mut ImageProcessor, horizontal: bool) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.flip(horizontal);
        ret
    })
}

fn image_processor_resize(it_: &mut ImageProcessor, width: f64, height: f64, fit: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.resize(width, height, fit);
        ret
    })
}

fn image_processor_rotate(it_: &mut ImageProcessor, degrees: f64) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.rotate(degrees);
        ret
    })
}

fn image_processor_save(it_: &mut ImageProcessor) -> Result<ImageResult, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.save();
        ret
    }).and_then(|r| r)
}

fn image_processor_set_file_path(it_: &mut ImageProcessor, path: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.set_file_path(path);
        ret
    })
}


