// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::image_processor_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::imageprocessor::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct ImageResult {
        base_64: String,
        width: f64,
        height: f64,
        format: String,
    }

    extern "Rust" {
        type ImageProcessor;

        #[cxx_name = "createImageProcessor"]
        fn create_image_processor(id: usize, data_path: &str) -> Box<ImageProcessor>;

        #[cxx_name = "loadImage"]
        fn image_processor_load_image(it_: &mut ImageProcessor, path: &str) -> Result<ImageResult>;
    }
}

fn create_image_processor(id: usize, data_path: &str) -> Box<ImageProcessor> {
    let ctx = Context::new(id, data_path);
    Box::new(ImageProcessor::new(ctx))
}

fn image_processor_load_image(it_: &mut ImageProcessor, path: &str) -> Result<ImageResult, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.load_image(path);
        ret
    }).and_then(|r| r)
}


