// Auto generated by Craby. DO NOT EDIT.
// Hash: 9d23307d3c891e2b
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ImageProcessorSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn load_image(&mut self, path: &str) -> Promise<ImageResult>;
}

impl Default for ImageResult {
    fn default() -> Self {
        ImageResult {
            base_64: String::default(),
            width: 0.0,
            height: 0.0,
            format: String::default()
        }
    }
}
