// Auto generated by Craby. DO NOT EDIT.
// Hash: de85d48dcf60e401
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ImageProcessorSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn compress(&mut self, quality: Number, format: &str) -> Void;
    fn crop(&mut self, x: Number, y: Number, width: Number, height: Number) -> Void;
    fn flip(&mut self, horizontal: Boolean) -> Void;
    fn resize(&mut self, width: Number, height: Number, fit: &str) -> Void;
    fn rotate(&mut self, degrees: Number) -> Void;
    fn save(&mut self) -> Promise<ImageResult>;
    fn set_file_path(&mut self, path: &str) -> Void;
}

impl Default for ImageResult {
    fn default() -> Self {
        ImageResult {
            uri: String::default(),
            width: 0.0,
            height: 0.0,
            format: String::default(),
            size: 0.0,
            compression_ratio: 0.0
        }
    }
}
